import type { Metadata } from "next";
import { PageContainer } from "@/components/layout/PageContainer";
export const metadata: Metadata = { title: "Manifesto", description: "The public declaration behind The Teff Papers." };
const paragraphs = [
  "Meaningful ideas rarely arrive as arguments ready to publish. They begin as a tension inside a project, a decision that refuses to become simple, a mistake that exposes an assumption, or a question that returns after the immediate work has moved on. Left in memory, those beginnings are easy to smooth over. Written down, they become easier to examine because the gaps, contradictions and connections can no longer hide inside familiarity. The idea starts to show not only what it says, but what it may be becoming.",
  "That is why I do not see writing as a record made after the real work is finished. Writing is often part of the work itself. It slows a decision enough for its reasoning to become visible, preserves the reason a project began and gives an assumption somewhere to be challenged before it becomes expensive. The principle “Document first. Build second.” is not an argument for delay; it is a reminder that implementation becomes clearer when the thinking beneath it has already been tested in language.",
  "The Teff Papers grew from that relationship between documentation and building. I needed a place where an idea could be followed carefully enough to understand what it was becoming, including the parts that had not yet resolved themselves. Writing creates that space. It allows a question to remain open without becoming vague, and it gives separate observations enough structure to reveal when they are connected. Some of those ideas may remain papers. Others may eventually inform research, products, companies or collaborations, but they deserve to be understood before the finished result becomes the only part anyone can see.",
  "The questions here move across artificial intelligence, human intelligence and judgement, automation, systems thinking, blockchain and digital infrastructure, entrepreneurship, technology, leadership, faith and purpose, human behaviour, and the products and decisions behind them. I do not treat these as separate territories. A technical system carries assumptions about people; a product reflects decisions about value; an incentive can reshape behaviour; and leadership is often revealed by the systems a person creates when direct supervision is absent. Following those connections is more useful to me than forcing every paper into a narrow subject.",
  "The writing must remain close to real work. Papers should emerge from projects, mistakes, observations, difficult decisions, recurring questions and the moments when experience refuses to fit the explanation I began with. Detached theory can describe a system from a safe distance, but working inside one reveals its trade-offs, constraints and unintended effects. That contact gives the writing something to test itself against. It also keeps me honest about the difference between an idea that sounds complete and one that has survived use.",
  "This approach changes what publishing is for. I am not trying to satisfy a schedule, chase trends or turn every passing thought into output. Attention can bring a reader to a page, but it cannot make the reasoning worth returning to. A paper succeeds when it makes the thinking clearer than it was before the writing began and gives the reader a useful question, a sharper distinction or a different way of seeing something familiar. “Never write to impress. Always write to clarify.” belongs inside that standard because clarity requires enough respect for the reader to show the reasoning rather than decorate the conclusion.",
  "Showing the reasoning does not mean pretending to have every answer. It means being precise about what I have observed, how one conclusion led to another and where the limits of the argument remain. The voice should feel confident without becoming absolute, personal without turning every paper into autobiography, and reflective without announcing that reflection before it has earned a place. What matters is that the writing reveals how I think, not only what I know, so a reader can follow the movement of the idea rather than receive a polished conclusion without its foundations.",
  "Public thinking also needs boundaries. Some ideas belong to products that are unfinished, collaborations that require trust or decisions whose details are not mine to disclose. The Papers can still examine the principles, mistakes and lessons surrounding that work without exposing confidential mechanisms or presenting incomplete plans as promises. Protecting what should remain private does not weaken the writing. It asks the paper to reach the level where the lesson can stand on its own, useful beyond the particular project that produced it.",
  "That distinction allows The Teff Papers to grow alongside whatever comes next without becoming a marketing layer for it. Research may deepen a question raised here. A product may test an argument in practice. A company or collaboration may create problems that demand better language and stronger reasoning. The relationship can move in both directions: writing can clarify what deserves to be built, while building can expose where the writing was incomplete. The Papers should remain capable of holding that exchange even when individual projects change.",
  "Growth also requires leaving earlier thinking visible. An archive becomes less honest when every old idea is rewritten to resemble the person looking back at it. Some papers will age well, some will need qualification and some may reveal assumptions I no longer hold. They should remain part of the record because development is easier to understand when its earlier stages have not been erased. New papers can correct, extend or disagree with older ones, allowing the change itself to become documented rather than presenting certainty as though it existed from the beginning.",
  "Over the years, readers should be able to expect careful reasoning, connected prose and ideas grounded in the realities of working, learning and building. They should also expect the subjects to expand as new questions appear and existing ones become more demanding. I cannot know which paper will lead to a product, which observation will become research or which question will remain unresolved for a long time. The useful commitment is smaller and more durable: to notice what deserves examination, document it with honesty and keep following the idea until its meaning becomes clearer."
];
export default function ManifestoPage() { return <PageContainer narrow className="paper-page"><article><header className="paper-header"><p className="eyebrow">Manifesto · Version 2.0</p><h1>The Teff Papers</h1><p className="paper-deck">Ideas should be documented before they become products.</p></header><div className="prose manifesto">{paragraphs.map((text, index) => <p key={`${index}-${text}`}>{text}</p>)}</div><footer className="paper-signature"><p>— Teff</p></footer></article></PageContainer>; }
